import {createTypes} from 'reduxsauce';

export default createTypes(`
  INITIALIZE
  INITIALIZE_SUCCESS
  
  SET_HAS_SEEN_WALKTHROUGH
  APP_STATE
  
  REGISTER
  REGISTER_SUCCESS
  REGISTER_FAILURE
  CLEAR_REGISTRATION_SUCCESS_MESSAGE

  REGISTER_PUSH
  REGISTER_PUSH_SUCCESS
  REGISTER_PUSH_FAILURE
  
  LOGIN
  LOGIN_SUCCESS
  LOGIN_FAILURE
  
  GET_TOKEN
  GET_TOKEN_SUCCESS
  GET_TOKEN_FAILURE

  LOGOUT
  
  GET_STOPS
  GET_STOPS_SUCCESS
  GET_STOPS_FAILURE
  
  GET_ETA
  GET_ETA_SUCCESS
  GET_ETA_FAILURE
  
  START_ETA_REFRESH_LOOP
  STOP_ETA_REFRESH_LOOP
  ETA_UPDATE_COUNTER
  ETA_REFRESH_LOOP_SUCCESS
  ETA_REFRESH_LOOP_FAILURE
  
  GET_STATES_AND_DISTRICTS
  GET_STATES_AND_DISTRICTS_SUCCESS
  GET_STATES_AND_DISTRICTS_FAILURE
  
  GET_ME
  GET_ME_SUCCESS
  GET_ME_FAILURE
  
  GET_PROFILE
  GET_PROFILE_SUCCESS
  GET_PROFILE_FAILURE
  
  GET_STUDENTS
  GET_STUDENTS_SUCCESS
  GET_STUDENTS_FAILURE
  
  ADD_STUDENT
  ADD_STUDENT_SUCCESS
  ADD_STUDENT_FAILURE
  
  REMOVE_STUDENT
  REMOVE_STUDENT_SUCCESS
  REMOVE_STUDENT_FAILURE
  
  ADD_FEEDBACK
  ADD_FEEDBACK_SUCCESS
  ADD_FEEDBACK_FAILURE
  
  SET_CONFIRMATION_DIALOG_MESSAGE
  CLEAR_CONFIRMATION_DIALOG_MESSAGE
  
  RESET_PASSWORD
  RESET_PASSWORD_SUCCESS
  RESET_PASSWORD_FAILURE

  GET_NOTIFICATIONS
  GET_NOTIFICATIONS_SUCCESS
  GET_NOTIFICATIONS_FAILURE

  REMOVE_NOTIFICATION
  REMOVE_NOTIFICATION_SUCCESS
  REMOVE_NOTIFICATION_FAILURE

  ONE_SIGNAL_IDS_AVAILABLE
  SUBSCRIBE_TO_ONE_SIGNAL
  UNSUBSCRIBE_FROM_ONE_SIGNAL
  
  VIEW_ONE_SIGNAL_DEVICE
  VIEW_ONE_SIGNAL_DEVICE_SUCCESS
  VIEW_ONE_SIGNAL_DEVICE_FAILURE

  GET_NOTIFICATION_PREFERENCES
  GET_NOTIFICATION_PREFERENCES_SUCCESS
  GET_NOTIFICATION_PREFERENCES_FAILURE

  ADD_NOTIFICATION_PREFERENCE
  ADD_NOTIFICATION_PREFERENCE_SUCCESS
  ADD_NOTIFICATION_PREFERENCE_FAILURE

  UPDATE_NOTIFICATION_PREFERENCE
  UPDATE_NOTIFICATION_PREFERENCE_SUCCESS
  UPDATE_NOTIFICATION_PREFERENCE_FAILURE

  REMOVE_NOTIFICATION_PREFERENCE
  REMOVE_NOTIFICATION_PREFERENCE_SUCCESS
  REMOVE_NOTIFICATION_PREFERENCE_FAILURE

  GET_NOTIFICATION_CONTACTS
  GET_NOTIFICATION_CONTACTS_SUCCESS
  GET_NOTIFICATION_CONTACTS_FAILURE

  ADD_NOTIFICATION_CONTACT
  ADD_NOTIFICATION_CONTACT_SUCCESS
  ADD_NOTIFICATION_CONTACT_FAILURE

  UPDATE_NOTIFICATION_CONTACT
  UPDATE_NOTIFICATION_CONTACT_SUCCESS
  UPDATE_NOTIFICATION_CONTACT_FAILURE

  REMOVE_NOTIFICATION_CONTACT
  REMOVE_NOTIFICATION_CONTACT_SUCCESS
  REMOVE_NOTIFICATION_CONTACT_FAILURE

  UPDATE_PROFILE
  UPDATE_PROFILE_SUCCESS
  UPDATE_PROFILE_FAILURE
`);
